package com.example.yoloaio.navigation

object Routes {
    const val AUTH = "auth"
    const val HOME = "home"
    const val SETTINGS = "settings"
    const val PRIVACY = "settings/privacy"
    const val AUDIO_TRIMMER = "audio_trimmer"
    const val CHAT = "chat"
    const val CHAT_CONVERSATION = "chat/{userId}"
    fun chatConversation(userId: String) = "chat/$userId"
    const val USER_PROFILE = "users/{uid}"
    fun userProfile(uid: String) = "users/$uid"
    const val MUSIC = "music"
    const val MUSIC_SETTINGS = "music/settings"
    const val MOVIES = "movies"
    const val MOVIE_DETAIL = "movies/{movieId}"
    fun movieDetail(movieId: String) = "movies/$movieId"
    const val MOVIE_PLAYER = "movies/{movieId}/play"
    fun moviePlayer(movieId: String) = "movies/$movieId/play"
    const val TV_DETAIL = "tv/{tvId}"
    fun tvDetail(tvId: String) = "tv/$tvId"
    const val TV_PLAYER = "tv/{tvId}/play/{season}/{episode}"
    fun tvPlayer(tvId: String, season: Int, episode: Int) = "tv/$tvId/play/$season/$episode"
    const val QUOTES = "quotes"
    const val QUOTE_EDITOR = "quotes/new"
    const val WALLPAPER = "wallpaper"
    const val WALLPAPER_FAVORITES = "wallpaper/favorites"
    const val WALLPAPER_DETAIL = "wallpaper/{wallpaperId}"
    fun wallpaperDetail(wallpaperId: String) = "wallpaper/$wallpaperId"
    const val RINGTONES = "ringtones"
    const val RINGTONE_FAVORITES = "ringtones/favorites"
    const val BOOKS = "books"
    const val BOOK_FAVORITES = "books/favorites"
    const val BOOK_READER = "books/{bookId}/read"
    fun bookReader(bookId: String) = "books/$bookId/read"
    const val BEAT_ANALYSER = "beat_analyser"
    const val WEATHER = "weather"
    const val WIFI_LAB = "wifi_lab"
    const val COMMUNITY = "community"
    const val VIDEOS = "videos"
    const val VIDEO_PLAYER = "videos/{videoId}/play"
    fun videoPlayer(videoId: String) = "videos/$videoId/play"
}
